// Generated by gencpp from file collision_check/CheckJointStateCollisionResponse.msg
// DO NOT EDIT!


#ifndef COLLISION_CHECK_MESSAGE_CHECKJOINTSTATECOLLISIONRESPONSE_H
#define COLLISION_CHECK_MESSAGE_CHECKJOINTSTATECOLLISIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace collision_check
{
template <class ContainerAllocator>
struct CheckJointStateCollisionResponse_
{
  typedef CheckJointStateCollisionResponse_<ContainerAllocator> Type;

  CheckJointStateCollisionResponse_()
    : success(false)
    , info()  {
    }
  CheckJointStateCollisionResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , info(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckJointStateCollisionResponse_

typedef ::collision_check::CheckJointStateCollisionResponse_<std::allocator<void> > CheckJointStateCollisionResponse;

typedef boost::shared_ptr< ::collision_check::CheckJointStateCollisionResponse > CheckJointStateCollisionResponsePtr;
typedef boost::shared_ptr< ::collision_check::CheckJointStateCollisionResponse const> CheckJointStateCollisionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace collision_check

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b014a3b1f45715ffd8087f5d5c89429";
  }

  static const char* value(const ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b014a3b1f45715fULL;
  static const uint64_t static_value2 = 0xfd8087f5d5c89429ULL;
};

template<class ContainerAllocator>
struct DataType< ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "collision_check/CheckJointStateCollisionResponse";
  }

  static const char* value(const ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string info\n"
"\n"
;
  }

  static const char* value(const ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckJointStateCollisionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::collision_check::CheckJointStateCollisionResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLLISION_CHECK_MESSAGE_CHECKJOINTSTATECOLLISIONRESPONSE_H
