// Generated by gencpp from file j2n6s300_ml/tfQueryRequest.msg
// DO NOT EDIT!


#ifndef J2N6S300_ML_MESSAGE_TFQUERYREQUEST_H
#define J2N6S300_ML_MESSAGE_TFQUERYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace j2n6s300_ml
{
template <class ContainerAllocator>
struct tfQueryRequest_
{
  typedef tfQueryRequest_<ContainerAllocator> Type;

  tfQueryRequest_()
    {
    }
  tfQueryRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct tfQueryRequest_

typedef ::j2n6s300_ml::tfQueryRequest_<std::allocator<void> > tfQueryRequest;

typedef boost::shared_ptr< ::j2n6s300_ml::tfQueryRequest > tfQueryRequestPtr;
typedef boost::shared_ptr< ::j2n6s300_ml::tfQueryRequest const> tfQueryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace j2n6s300_ml

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'j2n6s300_ml': ['/home/simon/sim2real/simulations/kinova/src/sim2Real_j2n6s300/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "j2n6s300_ml/tfQueryRequest";
  }

  static const char* value(const ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tfQueryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::j2n6s300_ml::tfQueryRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // J2N6S300_ML_MESSAGE_TFQUERYREQUEST_H
